env:
    browser: true
    es2020: true
extends:
    - standard
    - prettier
    - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 11
    sourceType: module
plugins:
    - "@typescript-eslint"
    - "prettier"
rules:
    {
        "@typescript-eslint/no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars-experimental": "error",
        "no-unused-vars": "off",
        "prettier/prettier": "error",
        "linebreak-style": ["error", "unix"],
    }
