service: datapm-registry

provider:
  name: google
  runtime: 'nodejs12'
  project: datapm-test
  credentials: ~/.gcloud/keyfile.json # path must be absolute
  environment:
    APOLLO_KEY: service:family-connections:asdfasdfasdfasdf
    APOLLO_GRAPH_VARIANT: dev
    GCLOUD_STORAGE_BUCKET_NAME: "datapm-registry"
    GOOGLE_CLOUD_PROJECT: adsfasdf
    GRAPHQL_CONTEXT_USER_SUB: auth0|adsfasdfasdfasdf
    FILESYSTEM_STORAGE_DIRECTORY: local_storage
    MIXPANEL_TOKEN: asdfasdfasdf
    TYPEORM_PORT: "5432"
    TYPEORM_DATABASE: postgres
    TYPEORM_SCHEMA: public
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: postgres
    SENDGRID_API_KEY: asdfasdfa
    GOOGLE_LOGIN_CLIENT_ID: 832769547626-tnldssk3ljco2icmss266tnn5epalheb.apps.googleusercontent.com
    GOOGLE_LOGIN_SECRET: p1YiHnsuBMHcyltiWL_1h5yt
    REGISTRY_HOSTNAME: localhost
    REGISTRY_PORT: "4000"

plugins:
  - serverless-google-cloudfunctions

package:
  include:
    - dist/**
  exclude:
    - .gitignore
    - .git/**

functions:
  one:
    handler: graphqlHandler
    events:
      - http: ANY {proxy+}
  two:
    handler: graphqlHandler
    events:
      - http: ANY /
