resources:
  - type: storage.v1.bucket
    name: sls-datapm-registry-dev-1598313883514
  - type: 'gcp-types/cloudfunctions-v1:projects.locations.functions'
    name: datapm-registry-dev-one
    properties:
      parent: projects/datapm-test/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs12
      timeout: 60s
      entryPoint: graphqlHandler
      function: datapm-registry-dev-one
      sourceArchiveUrl: >-
        gs://sls-datapm-registry-dev-1598313883514/serverless/datapm-registry/dev/1598325500508-2020-08-25T03:18:20.508Z/datapm-registry.zip
      environmentVariables:
        APOLLO_KEY: 'service:family-connections:asdfasdfasdfasdf'
        APOLLO_GRAPH_VARIANT: dev
        GCLOUD_STORAGE_BUCKET_NAME: datapm-registry
        GOOGLE_CLOUD_PROJECT: adsfasdf
        GCLOUD_CASE_EXPORT_BUCKET_NAME: case-export
        GRAPHQL_CONTEXT_USER_SUB: auth0|adsfasdfasdfasdf
        FILESYSTEM_STORAGE_DIRECTORY: local_storage
        MIXPANEL_TOKEN: asdfasdfasdf
        TYPEORM_PORT: '5432'
        TYPEORM_DATABASE: postgres
        TYPEORM_SCHEMA: public
        TYPEORM_USERNAME: postgres
        TYPEORM_PASSWORD: postgres
        SENDGRID_API_KEY: asdfasdfa
        GOOGLE_LOGIN_CLIENT_ID: >-
          832769547626-tnldssk3ljco2icmss266tnn5epalheb.apps.googleusercontent.com
        GOOGLE_LOGIN_SECRET: p1YiHnsuBMHcyltiWL_1h5yt
        REGISTRY_HOSTNAME: localhost
        REGISTRY_PORT: '4000'
      labels: {}
      httpsTrigger:
        url: 'ANY {proxy+}'
  - type: 'gcp-types/cloudfunctions-v1:projects.locations.functions'
    name: datapm-registry-dev-two
    properties:
      parent: projects/datapm-test/locations/us-central1
      availableMemoryMb: 256
      runtime: nodejs12
      timeout: 60s
      entryPoint: graphqlHandler
      function: datapm-registry-dev-two
      sourceArchiveUrl: >-
        gs://sls-datapm-registry-dev-1598313883514/serverless/datapm-registry/dev/1598325500508-2020-08-25T03:18:20.508Z/datapm-registry.zip
      environmentVariables:
        APOLLO_KEY: 'service:family-connections:asdfasdfasdfasdf'
        APOLLO_GRAPH_VARIANT: dev
        GCLOUD_STORAGE_BUCKET_NAME: datapm-registry
        GOOGLE_CLOUD_PROJECT: adsfasdf
        GCLOUD_CASE_EXPORT_BUCKET_NAME: case-export
        GRAPHQL_CONTEXT_USER_SUB: auth0|adsfasdfasdfasdf
        FILESYSTEM_STORAGE_DIRECTORY: local_storage
        MIXPANEL_TOKEN: asdfasdfasdf
        TYPEORM_PORT: '5432'
        TYPEORM_DATABASE: postgres
        TYPEORM_SCHEMA: public
        TYPEORM_USERNAME: postgres
        TYPEORM_PASSWORD: postgres
        SENDGRID_API_KEY: asdfasdfa
        GOOGLE_LOGIN_CLIENT_ID: >-
          832769547626-tnldssk3ljco2icmss266tnn5epalheb.apps.googleusercontent.com
        GOOGLE_LOGIN_SECRET: p1YiHnsuBMHcyltiWL_1h5yt
        REGISTRY_HOSTNAME: localhost
        REGISTRY_PORT: '4000'
      labels: {}
      httpsTrigger:
        url: ANY /
