env:
    browser: false
    es2020: true
extends:
    - standard
    - prettier
    - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: 11
    sourceType: module
plugins:
    - "prettier"
rules:
    {
        "@typescript-eslint/no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars-experimental": ["error", { ignoreArgsIfArgsAfterAreUsed: true }],
        "no-unused-vars": "off",
        "no-useless-constructor": "off",
        "@typescript-eslint/no-useless-constructor": "error",
        "no-use-before-define": "off",
        "prettier/prettier": "error",
    }
