name: "Build & Deploy"

on:
    push:
#        branches:
#            - master

jobs:
    lint:
        runs-on: ubuntu-latest
        timeout-minutes: 3
        name: Lint Source Code
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.18.3"

            - name: Print npm verion
              run: npm --version

            - name: Print node verion
              run: node --version

            - name: Install Root Dependencies
              run: npm ci

            - name: Run ESLint
              run: npm run lint

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v1

            - name: Terraform Format
              run: terraform fmt -check

    bumpVersion:
        name: "Bump Version"
        timeout-minutes: 5
        runs-on: "ubuntu-latest"
        needs: lint
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: "14.18.3"

            - name: Install Dependencies
              run: npm ci

            - name: Set Git Author
              run: git config user.name "$${{env.GITHUB_ACTOR}}" && git config user.email "gitHubActionDeployer@no-reply"

            - name: Bump Version
              run: npm run bump-version

    build-win-x64-client:
        runs-on: windows-latest
        timeout-minutes: 15
        needs: bumpVersion
        name: Windows Build DataPM Client
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.18.3"

            - name: Install Lib Dependencies
              run: npm ci
              working-directory: lib

            - name: Build Lib
              run: npm run build
              working-directory: lib

            - name: Link Lib
              run: npm link
              working-directory: lib/dist

            - name: Install client dependencies
              run: npm ci
              working-directory: client
              if: steps.cache-client-node-modules.outputs.cache-hit != 'true'

            - name: Link Lib for Client
              run: npm link datapm-lib
              working-directory: client

            - name: Run build
              run: npm run build
              working-directory: client

            - run: npm run package:win:x64
              working-directory: client
              env:
                  CERTIFICATE_BASE64: ${{ secrets.WINDOWS_CLIENT_CERTIFICATE_BASE64 }}
                  CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CLIENT_CERTIFICATE_PASSWORD }}

            - name: "Save Windows Executable"
              uses: actions/upload-artifact@v2
              with:
                  name: datapm-client-windows-x64
                  path: client/datapm-*-x64.msix
                  retention-days: 5

    build-macos-x64-client:
        runs-on: macos-latest
        timeout-minutes: 15
        needs: bumpVersion
        name: MacOS DataPM Client
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "14.18.3"

            - name: get-npm-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@master

            - name: Install Lib Dependencies
              run: npm ci
              working-directory: lib

            - name: Build Lib
              run: npm run build
              working-directory: lib

            - name: Link Lib
              run: npm link
              working-directory: lib/dist

            - name: Install client dependencies
              run: npm ci
              working-directory: client
              if: steps.cache-client-node-modules.outputs.cache-hit != 'true'

            - name: Link Lib for Client
              run: npm link datapm-lib
              working-directory: client

            - name: Run build
              run: npm run build
              working-directory: client

            - run: npm run package:macos:x64
              working-directory: client
              env:
                  CERTIFICATE_BASE64: ${{ secrets.WINDOWS_CLIENT_CERTIFICATE_BASE64 }}
                  CERTIFICATE_PASSWORD: ${{ secrets.WINDOWS_CLIENT_CERTIFICATE_PASSWORD }}

            - name: Codesign & Generate MacOS Installer
              env:
                  MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
                  MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
                  MACOS_KEYCHAIN_TEMPORARY_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_TEMPORARY_PASSWORD }}
                  APPLE_DEVELOPER_CERTIFICATE_ID: ${{secrets.APPLE_DEVELOPER_CERTIFICATE_ID}}
                  DATAPM_VERSION: ${{ steps.package-version.outputs.current-version}}
              run: |
                  echo $MACOS_CERTIFICATE | base64 -D > certificate.p12
                  security create-keychain -p $MACOS_KEYCHAIN_TEMPORARY_PASSWORD build.keychain 
                  security default-keychain -s build.keychain
                  security unlock-keychain -p $MACOS_KEYCHAIN_TEMPORARY_PASSWORD build.keychain
                  security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_KEYCHAIN_TEMPORARY_PASSWORD build.keychain
                  /usr/bin/codesign --force --options runtime --entitlements ./client/installers/macos/macOS-x64/macos-runtime-entitlements.plist -s $APPLE_DEVELOPER_CERTIFICATE_ID --timestamp ./client/pkg-mac64/datapm -v
                  cp -R ./client/pkg-mac64/* ./client/installers/macos/macOS-x64/application
                  cd client/installers/macos/macOS-x64
                  ./build-macos-x64.sh DataPM $DATAPM_VERSION

            - name: "Create MacOS Installer Artifact"
              uses: actions/upload-artifact@v2
              with:
                  name: datapm-client-windows-x64
                  path: ./client/installers/macos/macOS-x64/target/pkg-signed/*.dmg
                  retention-days: 7

    buildAndDeploy:
        name: "Build And Deploy"
        timeout-minutes: 20
        runs-on: ubuntu-latest
        needs:
            - build-macos-x64-client
            - build-win-x64-client
        if: false # DISABLED FOR TESTING
        env:
            INPUT_TOKEN: "" # See https://github.com/JS-DevTools/npm-publish/issues/15
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: "14.18.3"

            - name: Print npm verion
              run: npm --version

            - name: Print node verion
              run: node --version

            - name: Install Dependencies
              run: npm ci

            - name: Install Lib Dependencies
              id: install-lib-Dependencies
              run: npm ci
              working-directory: lib

            - name: Build Lib
              id: build-lib-Dependencies
              run: npm run build
              working-directory: lib

            - name: Link Lib
              run: npm link
              working-directory: lib/dist

            - uses: JS-DevTools/npm-publish@v1
              with:
                  package: ./lib/dist/package.json
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Bump Package Files Lib Versions
              run: npm run bump-package-lib-versions

            - name: Tag
              run: npm run tag

            - name: Install Backend Dependencies
              id: install-backend-Dependencies
              run: npm ci
              working-directory: backend

            - name: Link Lib for Backend
              run: npm link datapm-lib
              working-directory: backend

            - name: Build Backend
              id: build-backend-Dependencies
              run: npm run build
              working-directory: backend

            - name: Install Frontend Dependencies
              id: install-frontend-dependencies
              run: npm ci
              working-directory: frontend

            - name: Link Lib for Frontend
              run: npm link datapm-lib
              working-directory: frontend

            - name: Build Frontend
              id: build-frontend-Dependencies
              run: npm run build
              working-directory: frontend

            - name: Install Docs Dependencies
              id: install-docs-dependencies
              run: npm ci
              working-directory: docs/website

            - name: Build Docs
              id: build-docs-Dependencies
              run: npm run build
              working-directory: docs/website

            - name: Download Win64 Installer
              uses: actions/download-artifact@v2
              with:
                  name: datapm-client-windows-x64
                  path: dist/client-installers

            - name: Build Registry Docker Container
              run: gulp buildRegistryDockerImage

            - name: Smoke Test Registry Docker Image
              run: npm run test

            - name: Echo Docker Password to file
              run: echo $${{secrets.DOCKER_PASSWORD}} > ~/docker-password

            - name: Authorize Docker
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Write Credentials file
              run: echo $GOOGLE_CREDENTIALS > gcloud.key
              env:
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: Authenticate to Google Cloud
              run: gcloud auth activate-service-account deployment@datapm-test-terraform.iam.gserviceaccount.com --key-file=gcloud.key

            - name: Authorize Docker for GCR
              run: gcloud auth configure-docker --quiet

            - name: Deploy Assets
              run: npm run deploy
              env:
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: ~/gcloud.key

            - uses: JS-DevTools/npm-publish@v1
              with:
                  package: ./client/package.json
                  token: ${{ secrets.NPM_TOKEN }}

            - name: Terraform Init to
              run: terraform init
              env:
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: gcloud.key

            - name: Terraform Plan
              run: terraform plan
              env:
                  TF_VAR_APOLLO_KEY: ${{secrets.TF_VAR_APOLLO_KEY}}
                  TF_VAR_smtp_password: ${{secrets.TF_VAR_SMTP_PASSWORD}}
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: Add GCR Revision
              run: gcloud run deploy datapm-registry --project datapm-test-terraform --image gcr.io/datapm-test-terraform/datapm-registry --region us-central1 --platform managed
              env:
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: Terraform Apply
              run: terraform apply -auto-approve
              env:
                  TF_VAR_APOLLO_KEY: ${{secrets.TF_VAR_APOLLO_KEY}}
                  TF_VAR_smtp_password: ${{secrets.TF_VAR_SMTP_PASSWORD}}
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: Update GCR Traffic
              run: gcloud run services update-traffic datapm-registry --project datapm-test-terraform --region us-central1 --platform managed --to-latest
              env:
                  PROJECT_ID: data-test-terraform
                  GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}

            - name: Publish Apollo Graphql Update
              run: npx apollo service:push --graph=datapm --key=${{secrets.TF_VAR_APOLLO_KEY}} --variant=test --localSchemaFile=backend/dist/schema.gql,backend/dist/auth-schema.gql,backend/dist/user-schema.gql,backend/dist/api-key-schema.gql,backend/dist/images-schema.gql
              env:
                  INPUT_TOKEN: ${{ secrets.NPM_TOKEN }}

    github-release-clients:
        runs-on: ubuntu-latest
        name: "Client Releases on GitHub"
        needs:
            - "build-macos-x64-client"
            - "build-win-x64-client"
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Download Win64 Installer
              uses: actions/download-artifact@v2
              with:
                  name: datapm-client-windows-x64
                  path: dist/client-installers

            - name: Download MacOSx64 Installer
              uses: actions/download-artifact@v2
              with:
                  name: datapm-client-macos-x64
                  path: dist/client-installers

            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: |
                      dist/client-installers/*.msix
                      dist/client-installers/*.dmg
