name: 'Terraform'

on:
  push:
    branches:
    - master
    - v*

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: NPM Dependencies Install
      run: npm run ci

    - name: Build
      run: npm run build      

    - name: Deploy Assets
      run: npm run deploy

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Write Credentials file
      run: echo $GOOGLE_CREDENTIALS > ~/gcloud.key
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}       

    - name: Terraform Init
      run: terraform init
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ~/gcloud.key 

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} 

    - name: Terraform Apply
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}} 

    - name: Google Run Update
      run: gcloud run deploy datapm-registry --project datapm-test-terraform --image gcr.io/datapm-test-terraform/datapm-registry --region us-central1 --platform managed
      env:
        PROJECT_ID: data-test-terraform
        GOOGLE_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}